// <auto-generated />
using System;
using CodeToSurvive.DLL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeToSurvive.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20251224183220_InitGameDatabase")]
    partial class InitGameDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeToSurvive.DLL.Outfit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOwned")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("StyleBonus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Outfit");
                });

            modelBuilder.Entity("CodeToSurvive.DLL.OwnedOutfit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutfitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("StyleBonus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("OwnedOutfits");
                });

            modelBuilder.Entity("CodeToSurvive.DLL.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveLoan")
                        .HasColumnType("int");

                    b.Property<int>("CodingSkill")
                        .HasColumnType("int");

                    b.Property<int>("CreditScore")
                        .HasColumnType("int");

                    b.Property<int>("CurrentDay")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentOutfitId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentOutfitPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Energy")
                        .HasColumnType("int");

                    b.Property<int>("JobLevel")
                        .HasColumnType("int");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<int>("Reputation")
                        .HasColumnType("int");

                    b.Property<int>("Style")
                        .HasColumnType("int");

                    b.Property<int>("StyleLevel")
                        .HasColumnType("int");

                    b.Property<int>("TotalWorkDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentOutfitId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("CodeToSurvive.DLL.Outfit", b =>
                {
                    b.HasOne("CodeToSurvive.DLL.Player", null)
                        .WithMany("OwnedOutfits")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("CodeToSurvive.DLL.OwnedOutfit", b =>
                {
                    b.HasOne("CodeToSurvive.DLL.Player", "Player")
                        .WithMany("OwnedOutfit")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CodeToSurvive.DLL.Player", b =>
                {
                    b.HasOne("CodeToSurvive.DLL.Outfit", "CurrentOutfit")
                        .WithMany()
                        .HasForeignKey("CurrentOutfitId");

                    b.Navigation("CurrentOutfit");
                });

            modelBuilder.Entity("CodeToSurvive.DLL.Player", b =>
                {
                    b.Navigation("OwnedOutfit");

                    b.Navigation("OwnedOutfits");
                });
#pragma warning restore 612, 618
        }
    }
}
